# Generated by Django 5.2.7 on 2025-10-31 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jugadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('dni', models.IntegerField(unique=True)),
                ('años', models.DecimalField(decimal_places=0, max_digits=2)),
                ('fecha_nacimiento', models.DateField()),
                ('dorsal', models.DecimalField(decimal_places=0, max_digits=2, unique=True)),
                ('apodo', models.CharField(max_length=45, null=True)),
                ('fecha_contratacion', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mobiliario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('marca', models.CharField(max_length=75)),
                ('numero_serie', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patrocinadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('numero_interno', models.IntegerField(unique=True)),
                ('fecha_incorporacion', models.DateField(null=True)),
                ('financiamiento', models.IntegerField()),
            ],
        ),
    ]
