# Generated by Django 5.2.7 on 2025-10-29 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cancha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_cancha', models.IntegerField(max_length=1, unique=True)),
                ('tipo', models.CharField()),
                ('descripcion', models.CharField(max_length=100)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(default='0f51d20e6d67421ea1e6881d867b5815', max_length=32, unique=True)),
            ],
        ),
    ]
