# Generated by Django 5.2.7 on 2025-10-31 20:01

import reservas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cancha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_cancha', models.DecimalField(decimal_places=0, max_digits=1, unique=True)),
                ('tipo', models.CharField()),
                ('descripcion', models.CharField(max_length=100)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(default=reservas.models.generar_code, max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=75)),
                ('apellido', models.CharField(max_length=75)),
                ('dni', models.DecimalField(decimal_places=0, max_digits=8, unique=True)),
                ('nro_matricula', models.DecimalField(decimal_places=0, max_digits=6, unique=True)),
                ('telefono', models.IntegerField()),
                ('especialidad', models.CharField(max_length=100)),
                ('code', models.CharField(default=reservas.models.generar_code, max_length=32, unique=True)),
            ],
        ),
    ]
