# Generated by Django 5.2.7 on 2025-10-29 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancha',
            name='code',
            field=models.CharField(default='c7ec5d5bff4b4aab8785fddaf7bb8a76', max_length=32, unique=True),
        ),
    ]
