# Generated by Django 5.2.7 on 2025-10-29 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_alter_cancha_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancha',
            name='code',
            field=models.CharField(default='a41ac20906ff42d2a53ab8209f98da04', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='cancha',
            name='nro_cancha',
            field=models.DecimalField(decimal_places=0, max_digits=1, unique=True),
        ),
    ]
